import * as fs from 'fs';
import * as path from 'path';

// リスト内のデータ形式
export type ListItem = { 
  name: string; 
  value: any; 
  [key: string]: any 
};

export class SQLPlusEngine {
  private lists: Map<string, ListItem[]> = new Map();
  private history: string[] = [];

  /**
   * @param logFilePath 履歴（ログ）の保存先
   */
  constructor(private logFilePath: string = 'sqlplus_activity.log') {
    this.logAction("SQL+ Engine Initialized");
  }

  /**
   * JSロジック（js.runやjs.if）の中で「ddt」として使えるインターフェース
   */
  private get ddtContext() {
    return {
      read: (name: string) => this.lists.get(name) || [],
      count: (name: string) => (this.lists.get(name) || []).length,
      has: (name: string, key: string) => (this.lists.get(name) || []).some(i => i.name === key),
      exec: (cmd: string) => this.execute(cmd),
      listNames: () => Array.from(this.lists.keys())
    };
  }

  /**
   * メイン実行メソッド：すべての命令はここを通ります
   */
  public execute(command: string): any {
    const timestamp = new Date().toISOString();
    this.logAction(`Execute: ${command}`);

    // --- 1. JS連携・条件分岐系 (SQL+) ---
    if (command.startsWith("js.run(")) {
      const code = this.extractArgs(command);
      return new Function('ddt', code)(this.ddtContext);
    }

    if (command.startsWith("js.if(")) {
      const [cond, tCmd, fCmd] = this.parseCSVArgs(command);
      const isTrue = new Function('ddt', `return ${cond}`)(this.ddtContext);
      return isTrue ? this.execute(tCmd) : (fCmd ? this.execute(fCmd) : null);
    }

    if (command.startsWith("js.switch(")) {
      const [targetExpr, ...cases] = this.parseCSVArgs(command);
      const targetVal = new Function('ddt', `return ${targetExpr}`)(this.ddtContext);
      for (const c of cases) {
        const [val, cmd] = c.split(":").map(s => s.trim());
        if (val === String(targetVal) || val === "default") return this.execute(cmd);
      }
    }

    if (command.startsWith("js.try(")) {
      const [mainCmd, catchPart] = this.parseCSVArgs(command);
      try {
        return this.execute(mainCmd);
      } catch (e: any) {
        return this.execute(catchPart.replace("catch:", "").trim());
      }
    }

    // --- 2. SQL風リスト操作系 ---
    const tokens = command.split(".");
    if (tokens[0] === "list") {
      const listName = tokens[1];
      const actionRaw = tokens[2];
      
      if (!this.lists.has(listName)) this.lists.set(listName, []);
      const list = this.lists.get(listName)!;

      // add(名前, 値)
      if (actionRaw.startsWith("add(")) {
        const [name, value] = this.parseCSVArgs(actionRaw);
        list.push({ 
          name, 
          value: isNaN(Number(value)) ? value : Number(value) 
        });
        return "Added";
      }

      // read(options) -> 1.name="Taro",value="1" 形式
      if (actionRaw.startsWith("read(")) {
        const opts = this.extractArgs(actionRaw);
        return list.map((item, i) => {
          const order = i + 1;
          let str = `${order}.`;
          const parts: string[] = [];
          if (opts.includes("name")) parts.push(`name="${item.name}"`);
          if (opts.includes("value")) parts.push(`value="${order}"`);
          
          return parts.length > 0 ? `${str}${parts.join(",")}` : `${str}${item.name}:${item.value}`;
        });
      }

      // count(), sum(), unique(), delete(all/index=N)
      if (actionRaw === "count()") return list.length;
      if (actionRaw === "sum()") return list.reduce((a, b) => a + (Number(b.value) || 0), 0);
      if (actionRaw === "unique()") {
        const seen = new Set();
        this.lists.set(listName, list.filter(i => !seen.has(i.name) && seen.add(i.name)));
        return "Uniqued";
      }
      if (actionRaw === "delete(all)") { list.length = 0; return "Cleared"; }
      if (actionRaw.startsWith("delete(index=")) {
        const idx = parseInt(actionRaw.match(/\d+/)![0]) - 1;
        list.splice(idx, 1);
        return "Deleted";
      }
    }

    // --- 3. ファイル・フォルダ・履歴生成系 ---
    if (command.startsWith("file.mkdir(")) {
      const dir = this.extractArgs(command);
      fs.mkdirSync(dir, { recursive: true });
      return `Dir Created: ${dir}`;
    }

    if (command.startsWith("file.write(")) {
      const [filePath, content] = this.parseCSVArgs(command);
      // 履歴データも含めて保存
      const outputData = {
        _sqlplus_meta: {
          timestamp,
          command,
          description: "Auto-generated by SQL+"
        },
        data: content
      };
      fs.mkdirSync(path.dirname(filePath), { recursive: true });
      fs.writeFileSync(filePath, JSON.stringify(outputData, null, 2));
      return `File Written with History: ${filePath}`;
    }

    return "Command not recognized";
  }

  // --- ユーティリティ ---
  private logAction(msg: string) {
    const entry = `[${new Date().toISOString()}] ${msg}`;
    this.history.push(entry);
    fs.appendFileSync(this.logFilePath, entry + '\n');
  }

  private extractArgs(cmd: string): string {
    const match = cmd.match(/\((.*)\)/s);
    return match ? match[1] : "";
  }

  private parseCSVArgs(cmd: string): string[] {
    const argsString = this.extractArgs(cmd);
    if (!argsString) return [];
    // カンマで分割するが、カッコ内のカンマは無視する簡易パース
    return argsString.split(/,(?![^\(]*\))/).map(s => s.trim());
  }
}
